// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  GetCompanyGraphData,
  GetCompanyGraphErrors,
  GetCompanyGraphResponses,
  GetOfficerGraphData,
  GetOfficerGraphErrors,
  GetOfficerGraphResponses,
  SearchCompaniesData,
  SearchCompaniesErrors,
  SearchCompaniesResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Corporate network graph for a company
 *
 * Returns the company plus all its officers and PSCs (active and resigned/ceased) as a node/edge list. Add ?depth=2 to also expand each active officer's other current appointments.
 */
export const getCompanyGraph = <ThrowOnError extends boolean = false>(
  options: Options<GetCompanyGraphData, ThrowOnError>,
): RequestResult<
  GetCompanyGraphResponses,
  GetCompanyGraphErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCompanyGraphResponses,
    GetCompanyGraphErrors,
    ThrowOnError
  >({ url: "/api/company/{company_number}/graph", ...options });

/**
 * Appointments graph for an officer
 *
 * Returns the officer plus all companies they currently sit on the board of.
 */
export const getOfficerGraph = <ThrowOnError extends boolean = false>(
  options: Options<GetOfficerGraphData, ThrowOnError>,
): RequestResult<
  GetOfficerGraphResponses,
  GetOfficerGraphErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOfficerGraphResponses,
    GetOfficerGraphErrors,
    ThrowOnError
  >({ url: "/api/officer/{officer_id}/graph", ...options });

/**
 * Search companies by name
 *
 * Searches the requested country's company registry by name or number and returns matching companies for display as search result cards.
 */
export const searchCompanies = <ThrowOnError extends boolean = false>(
  options?: Options<SearchCompaniesData, ThrowOnError>,
): RequestResult<
  SearchCompaniesResponses,
  SearchCompaniesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SearchCompaniesResponses,
    SearchCompaniesErrors,
    ThrowOnError
  >({ url: "/api/search", ...options });
