// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Edge = {
  /**
   * Relationship type: officer_of or psc_of
   */
  kind: string;
  /**
   * Source node ID
   */
  source: string;
  /**
   * Target node ID
   */
  target: string;
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type Node = {
  /**
   * Stable node identifier, e.g. company:{number}, officer:{id}, psc:{name_slug}
   */
  id: string;
  /**
   * Display name for the node
   */
  label: string;
  /**
   * Type-specific metadata and visual hints for the Polaroid card renderer
   */
  meta: NodeMeta;
  /**
   * Node type: company, officer, or psc
   */
  type: string;
};

export type NodeMeta = {
  /**
   * True if statutory accounts are overdue — root company node only
   */
  accounts_overdue?: boolean;
  /**
   * Registered office address snippet — company nodes only
   */
  address?: string;
  /**
   * Appointment start date, ISO 8601 — officer and PSC nodes
   */
  appointed_on?: string;
  /**
   * Date the PSC ceased, ISO 8601, if ceased — PSC nodes only
   */
  ceased_on?: string;
  /**
   * Companies House number (UK) or GEMI number (GR) — company nodes only
   */
  company_number?: string;
  /**
   * Legal form, e.g. ltd, plc — company nodes only
   */
  company_type?: string;
  /**
   * True if the confirmation statement is overdue — root company node only
   */
  confirmation_statement_overdue?: boolean;
  /**
   * True if this node's connections have already been fetched and rendered
   */
  expanded: boolean;
  /**
   * True if the company has registered charges — root company node only
   */
  has_charges?: boolean;
  /**
   * True if the company has insolvency history — root company node only
   */
  has_insolvency_history?: boolean;
  /**
   * Date of incorporation, ISO 8601 — company nodes only
   */
  incorporation_date?: string;
  /**
   * Officer nationality — officer nodes only
   */
  nationality?: string;
  /**
   * Nature(s) of control held — PSC nodes only
   */
  natures_of_control?: Array<string> | null;
  /**
   * Date the PSC was notified, ISO 8601 — PSC nodes only
   */
  notified_on?: string;
  /**
   * Officer occupation — officer nodes only
   */
  occupation?: string;
  /**
   * Officer identifier — officer nodes only
   */
  officer_id?: string;
  /**
   * Deep-link to the entity on its source registry site, where available
   */
  registry_url?: string;
  /**
   * Resignation date, ISO 8601, if resigned — officer nodes only
   */
  resigned_on?: string;
  /**
   * Officer role, e.g. director, secretary — officer nodes only
   */
  role?: string;
  /**
   * SIC classification codes — company nodes only
   */
  sic_codes?: Array<string> | null;
  /**
   * Company status, e.g. active, dissolved — company nodes only
   */
  status?: string;
};

export type Response = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Directed relationships between nodes
   */
  edges: Array<Edge> | null;
  /**
   * Graph nodes: companies, officers, and PSCs
   */
  nodes: Array<Node> | null;
};

export type SearchResult = {
  /**
   * Short registered address snippet
   */
  address_snippet: string;
  /**
   * Company identifier (CH number for UK, GEMI number for GR)
   */
  company_number: string;
  /**
   * Date of incorporation, ISO 8601
   */
  date_of_creation?: string;
  /**
   * Registered company name
   */
  name: string;
  /**
   * Company status, e.g. active, dissolved
   */
  status: string;
  /**
   * Legal form, e.g. ltd, plc
   */
  type: string;
};

export type ErrorModelWritable = {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type ResponseWritable = {
  /**
   * Directed relationships between nodes
   */
  edges: Array<Edge> | null;
  /**
   * Graph nodes: companies, officers, and PSCs
   */
  nodes: Array<Node> | null;
};

export type GetCompanyGraphData = {
  body?: never;
  path: {
    /**
     * Company identifier (CH number for UK, GEMI number for GR)
     */
    company_number: string;
  };
  query?: {
    /**
     * Graph expansion depth: 1=direct connections (default), 2=connections of connections
     */
    depth?: number;
    /**
     * Country code: uk (default), gr
     */
    country?: string;
  };
  url: "/api/company/{company_number}/graph";
};

export type GetCompanyGraphErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetCompanyGraphError =
  GetCompanyGraphErrors[keyof GetCompanyGraphErrors];

export type GetCompanyGraphResponses = {
  /**
   * OK
   */
  200: Response;
};

export type GetCompanyGraphResponse =
  GetCompanyGraphResponses[keyof GetCompanyGraphResponses];

export type GetOfficerGraphData = {
  body?: never;
  path: {
    /**
     * Officer identifier
     */
    officer_id: string;
  };
  query?: {
    /**
     * Country code: uk (default), gr
     */
    country?: string;
  };
  url: "/api/officer/{officer_id}/graph";
};

export type GetOfficerGraphErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetOfficerGraphError =
  GetOfficerGraphErrors[keyof GetOfficerGraphErrors];

export type GetOfficerGraphResponses = {
  /**
   * OK
   */
  200: Response;
};

export type GetOfficerGraphResponse =
  GetOfficerGraphResponses[keyof GetOfficerGraphResponses];

export type SearchCompaniesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Company name or number to search for
     */
    q?: string;
    /**
     * Country code: uk (default), gr
     */
    country?: string;
  };
  url: "/api/search";
};

export type SearchCompaniesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type SearchCompaniesError =
  SearchCompaniesErrors[keyof SearchCompaniesErrors];

export type SearchCompaniesResponses = {
  /**
   * OK
   */
  200: Array<SearchResult> | null;
};

export type SearchCompaniesResponse =
  SearchCompaniesResponses[keyof SearchCompaniesResponses];
